Fix build failures
ERROR in src/main/ui/app/components/flows-new/edit-flow/mastering/ui/matching-ui.component.html(19,17): : Expected 2 arguments, but got 1.
src/main/ui/app/components/flows-new/edit-flow/mastering/ui/matching-ui.component.html(158,9): : Property 'openMatchThresholdDialog' does not exist on type 'MatchingUiComponent'.